# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ANP.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from turtle import onclick
from PyQt5 import QtCore, QtGui, QtWidgets
import AddPerson


class Ui_On_click_ANP(object):
    def setupUi(self, On_click_ANP):
        On_click_ANP.setObjectName("On_click_ANP")
        On_click_ANP.resize(400, 300)
        self.Name = QtWidgets.QTextEdit(On_click_ANP)
        self.Name.setGeometry(QtCore.QRect(80, 60, 221, 31))
        self.Name.setObjectName("Name")

        
        self.Roll = QtWidgets.QTextEdit(On_click_ANP)
        self.Roll.setGeometry(QtCore.QRect(80, 110, 221, 31))
        self.Roll.setObjectName("Roll")
        self.Ok_btn = QtWidgets.QPushButton(On_click_ANP)
        self.Ok_btn.setGeometry(QtCore.QRect(170, 170, 51, 28))
        self.Ok_btn.setObjectName("Ok_btn")
    
        self.Ok_btn.clicked.connect(lambda : self.onclick_ok())

        self.retranslateUi(On_click_ANP)
        QtCore.QMetaObject.connectSlotsByName(On_click_ANP)

    def retranslateUi(self, On_click_ANP):
        _translate = QtCore.QCoreApplication.translate
        On_click_ANP.setWindowTitle(_translate("On_click_ANP", "ANP"))
        self.Name.setPlaceholderText(_translate("On_click_ANP", "Enter Name : "))
        self.Roll.setPlaceholderText(_translate("On_click_ANP", "Enter Roll No : "))
        self.Ok_btn.setText(_translate("On_click_ANP", "Ok"))

    def onclick_ok(self):
        name = self.Name.toPlainText()
        roll = self.Roll.toPlainText()
        AddPerson.AddPerson(name,roll)
        self.On_click_ANP.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    On_click_ANP = QtWidgets.QDialog()
    ui = Ui_On_click_ANP()
    ui.setupUi(On_click_ANP)
    On_click_ANP.show()
    sys.exit(app.exec_())
    #ui.close()
