# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from main import main
from AddNewGuy import Ui_On_click_ANP

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(700, 500)
        self.Add_New_Person = QtWidgets.QPushButton(Dialog)
        self.Add_New_Person.setGeometry(QtCore.QRect(275, 210, 130, 25))
        self.Add_New_Person.setObjectName("Add_New_Person")
    

        self.Take_Attendance = QtWidgets.QPushButton(Dialog)
        self.Take_Attendance.setGeometry(QtCore.QRect(275, 280, 130, 25))
        self.Take_Attendance.setObjectName("Take_Attendance")
        m = main()
        self.Take_Attendance.clicked.connect(lambda : m.runCamera())

        self.Exit = QtWidgets.QPushButton(Dialog)
        self.Exit.setGeometry(QtCore.QRect(275, 350, 130, 25))
        self.Exit.setObjectName("Exit")
        self.Exit.clicked.connect(lambda:self.close())
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Face Recoginition"))
        self.Add_New_Person.setText(_translate("Dialog", "Add New Person"))
        self.Take_Attendance.setText(_translate("Dialog", "Take Attendance"))
        self.Exit.setText(_translate("Dialog", "Exit"))

class dialogMain(QtWidgets.QDialog, Ui_Dialog):
    def __init__(self, parent=None):
        super(dialogMain, self).__init__(parent)
        self.setupUi(self)
        self.Add_New_Person.clicked.connect(lambda: self.hide())


class dialogANP(QtWidgets.QDialog, Ui_On_click_ANP):
    def __init__(self, parent=None):
        super(dialogANP, self).__init__(parent)
        self.setupUi(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    w1 = dialogMain()
    w2 = dialogANP()
    w1.Add_New_Person.clicked.connect(w2.show)
    w2.Ok_btn.clicked.connect(w1.show)
    w1.show()
    sys.exit(app.exec_())
