# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ANP.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_On_click_ANP(object):
    def setupUi(self, On_click_ANP):
        On_click_ANP.setObjectName("On_click_ANP")
        On_click_ANP.resize(440, 505)
        self.Name = QtWidgets.QTextEdit(On_click_ANP)
        self.Name.setGeometry(QtCore.QRect(50, 390, 221, 31))
        self.Name.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.Name.setTabChangesFocus(True)
        self.Name.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.Name.setObjectName("Name")
        self.Roll = QtWidgets.QTextEdit(On_click_ANP)
        self.Roll.setGeometry(QtCore.QRect(390, 390, 221, 31))
        self.Roll.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhMultiLine)
        self.Roll.setTabChangesFocus(True)
        self.Roll.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.Roll.setObjectName("Roll")
        self.Ok_btn = QtWidgets.QPushButton(On_click_ANP)
        self.Ok_btn.setGeometry(QtCore.QRect(290, 450, 80, 26))
        self.Ok_btn.setObjectName("Ok_btn")
        self.graphicsView = QtWidgets.QGraphicsView(On_click_ANP)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 641, 371))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(On_click_ANP)
        self.label.setGeometry(QtCore.QRect(70, 450, 58, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/89850018.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(On_click_ANP)
        QtCore.QMetaObject.connectSlotsByName(On_click_ANP)

    def retranslateUi(self, On_click_ANP):
        _translate = QtCore.QCoreApplication.translate
        On_click_ANP.setWindowTitle(_translate("On_click_ANP", "ANP"))
        self.Name.setPlaceholderText(_translate("On_click_ANP", "Enter Name : "))
        self.Roll.setPlaceholderText(_translate("On_click_ANP", "Enter Roll No : "))
        self.Ok_btn.setText(_translate("On_click_ANP", "Ok"))
